### ISSUE TITLE
apprise_example.yml missing from repo

### ISSUE THREAD

**Issue by plt-francesco** [lorcalhost/BTB-manager-telegram#100]
Hi, I'm trying to setup the telegram bot but I cannot find the apprise_example.yml file. I don't think it is in the repo at all:
```
~/binance-trade-bot/BTB-manager-telegram $ grep -R apprise_example.yml $(pwd)
~/binance-trade-bot/BTB-manager-telegram/docs/telegram-setup.md:2. Copy the contents of `apprise_example.yml` into it.
```

**Comment by eudora-fabia** [comment]
@plt-francesco You should have it in the binance-trade-bot repository. Which is assumed to be installed beside the BTB-manager-telegram directory.

**Comment by plt-francesco** [comment]
> @plt-francesco You should have it in the binance-trade-bot repository. Which is assumed to be installed beside the BTB-manager-telegram directory. 

Well that makes sense. Thanks
