### ISSUE TITLE
Bot is not running? BTB-manager-telegram folder and binance-trade-bot folder in the same directory

### ISSUE THREAD

**Issue by defidummy** [lorcalhost/BTB-manager-telegram#112]
My bot is not running. Is this considered same directory?
I have both BTB-Manager_telegram folder and binance-trade-bot-master folder in downloads folder?
<img width="738" alt="Screen Shot 2021-06-07 at 4 17 03 PM" src="https://user-images.githubusercontent.com/82065755/121099019-eded0280-c7ab-11eb-8e5e-1b6dc78632b9.png">

**Comment by Teddy-Zhu** [comment]
bot folder's name is wrong , it's should be 'binance-trade-bot'
