### ISSUE TITLE
Add support for venv

### ISSUE THREAD

**Issue by titulebolide** [lorcalhost/BTB-manager-telegram#113]
Hi there! 

It would be eventually nice to add an option at the manager's startup to specify binance-trade-bot's virtualenv if it is unsing one. Because it is using the base python3. But i like to keep my dependencies under a venv to avoid pip conflicts between different projects...

Otherwise the manager and the binance trade bot could be sharing the same venv. If the manager detects it is being runned in a venv, it starts BTB in the same venv.

**Comment by titulebolide** [comment]
It cloud be changed this way (https://github.com/lorcalhost/BTB-manager-telegram/blob/2dd8a8c32352e6cb15eb76d727c319adcfeb12a7/btb_manager_telegram/buttons.py#L311)
```python
python_path = "$(which python3)"
if os.environ.get('VIRTUAL_ENV') is not None:
    python_path = os.path.join(
        os.environ.get('VIRTUAL_ENV'),
        'bin/python'
    )
subprocess.call(
    f"cd {settings.ROOT_PATH} && {python_path} -m binance_trade_bot &",
    shell=True,   
)
```

**Comment by lorcalhost** [comment]
That's a neat proposal, thanks for sharing.  
This will definitely go on the to do list.

**Comment by titulebolide** [comment]
I'll eventually make a PR when I'll have time with the according documentation.

What seems preferable? A shared venv or to specify btb'v venv though the cli?

**Comment by titulebolide** [comment]
Closing this issue as I opened the PR #116
