### ISSUE TITLE
Extend documentation for Custom scripts setup

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#114]
There are a lot of questions about custom scripts at discord like:
* what is the base dir from where scripts are taken
* how to add execution permission on script
* etc

Also, I recommend adding [that script](https://discord.com/channels/811277527997087745/818862057704390700/851190591454314539) as an example of executable script in example.json file.

**Comment by andrijvirt** [comment]
By default, all scripts that are executed from the BTB-manager-telegram's directory.

```
cd /path/to/the/BTB-manager-telegram
```

Create a folder where all your custom scripts will be stored and move to it:

```
mkdir custom_scripts
cd custom_scripts
```

Create the script, for example you may use the [example](https://discord.com/channels/811277527997087745/818862057704390700/851190591454314539) from our discord. Make it executable:

```
chmod +x filename.sh
```

In our example, we are using sqlite3 , so it is necessary to install it via system package manager 
```
sudo apt install sqlite3
```

Now we need to modify the custom_scripts.json (it is located here ~/BTB-manager-telegram/config/custom_scripts.json) file as in the example
```
{
  "Your script": "custom_scripts/filename.sh"
}
```

Do not forget to restart BTB-manager-telegram bot so the changes will be applied
