### ISSUE TITLE
Available update spams

### ISSUE THREAD

**Issue by Lisiadito** [lorcalhost/BTB-manager-telegram#118]
When an update is available and the bot spams every 5-10 seconds the message and no other button reacts on input. 
I run the bot with pm2. 

![image](https://user-images.githubusercontent.com/13214912/121493090-c2e6f680-c9d7-11eb-8e1c-b2e76b2e2159.png)

**Comment by lorcalhost** [comment]
This behavior is quite unexpected, as you can see here the message should only be sent every 12 hours:
https://github.com/lorcalhost/BTB-manager-telegram/blob/0f6049fb2b77f97c039b53c11108835ccfe19eae/btb_manager_telegram/utils.py#L150-L205

I'll look more into it but I suspect it's some kind of incompatibility with pm2

**Comment by titulebolide** [comment]
I've experienced the same and it looks like BTB is crashing and restarting over and over

**Comment by Lisiadito** [comment]
@titulebolide No I'm using pm2 which also does a auto restart on crash. In the end I also updated manually.

**Comment by titulebolide** [comment]
Any news on this?
