### ISSUE TITLE
Ratios not displaying correctly

### ISSUE THREAD

**Issue by bamooxa** [lorcalhost/BTB-manager-telegram#119]
Line 216 of buttons.py, this formula is used to calculate for telegram:
_( current_coin_price / other_coin_price ) - 0.001 * '{scout_multiplier}' * ( current_coin_price / other_coin_price ) ) - sh.target_ratio )_
The 0.001 should be atleast gathered from the variable the binance_trade_bot uses. If that isn't possible, it should be 0.002.

Line 131 of Edeng's binance trade bot uses:
_coin_opt_coin_ratio - transaction_fee * self.config.SCOUT_MULTIPLIER * coin_opt_coin_ratio - pair.ratio_

And a couple lines above that:

_transaction_fee = self.manager.get_fee(pair.from_coin, self.config.BRIDGE, True) + self.manager.get_fee(                pair.to_coin, self.config.BRIDGE, False)_

The resulting transaction_fee = 0.002 (for VIP 0 binance without any discounts).

**Comment by lorcalhost** [comment]
Thanks for pointing it out, we are aware of problems in the calculation method and will push a fix as soon as we have some time!

**Comment by titulebolide** [comment]
Is this still the case? We had some improvement for the ratio calculation, can you confirm?
