### ISSUE TITLE
Prepare the bot for BTB websocket version release

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#13]
This PR will soon be merged into the main branch.  
Compatibility issues should be investigated and fixed.  
https://github.com/edeng23/binance-trade-bot/pull/211

**Comment by bloodf** [comment]
I'm using with this PR and it's all fine till now

**Comment by lorcalhost** [comment]
There are reports of PR edeng23/binance-trade-bot#211 breaking the _Coin ratios_ feature.

**Comment by lorcalhost** [comment]
No further problems have been reported after the websockets merge into the main branch, closing the issue.
