### ISSUE TITLE
Invalid % of "1 day value change USD"

### ISSUE THREAD

**Issue by shhhmel** [lorcalhost/BTB-manager-telegram#130]
![photo_2021-08-04 16 28 13](https://user-images.githubusercontent.com/17930913/128189673-6a36bf9f-6080-47d7-857c-c77fd55d9f0a.jpeg)

**Comment by shhhmel** [comment]
Similar to this one: https://github.com/lorcalhost/BTB-manager-telegram/issues/129

**Comment by titulebolide** [comment]
Probably fixed by this one : #143

**Comment by titulebolide** [comment]
It's supposed to be fixed now with the addition of reports.
