### ISSUE TITLE
Bot doesn't respond to commands after starting the trading bot using the telegram command

### ISSUE THREAD

**Issue by sokffa** [lorcalhost/BTB-manager-telegram#138]
Im having trouble with the bot.
after clicking "Start trade bot" the bot displays the crypto_trading_logger but then stops responding to my commands
I click "Back" but nothing happens.
The only thing that worked for me is starting the trading bot and the telegram bot separately. But then when I try to restart it using the commands I fall into the same problem.

**Comment by titulebolide** [comment]
Any update on this?

**Comment by titulebolide** [comment]
Closing for now.

**Comment by HaidarWahid** [comment]
Hi, 
Is this solve ?

**Comment by HaidarWahid** [comment]
Reopen this issue [#226](https://github.com/lorcalhost/BTB-manager-telegram/issues/226)

**Comment by sokffa** [comment]
The problem was in fact related an OOM killing the subprocess of the trading bot launched by the Telegram bot process

**Comment by ToTheMoon365** [comment]
Did You get to work ?
