### ISSUE TITLE
user.cfg backup file is created with different permissions than the original file

### ISSUE THREAD

**Issue by schrottgerardo** [lorcalhost/BTB-manager-telegram#147]
I found that after use the **Edit user.cfg** button, a backup file is created, but the new file has not the sames file permissions:

> -rw------- 1 user  user     343 Nov 13 15:54 user.cfg
> -rw-r--r-- 1 user  user     344 Nov 13 15:54 user.cfg.backup

That's no fun, any other user could know the _api_token_ and _api_secret_token_ by reading the backup file.

I think it can be easily fixed, using `shutil.copymode()` after the `shutil.copyfile()` method, inside the edit_user_config handler.

**Comment by titulebolide** [comment]
Hi, thanks for reporting this.
I'll give it a look

**Comment by titulebolide** [comment]
Done in the latest commit.
