### ISSUE TITLE
Separate script into multiple files

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#19]
Now that `BTB-manager-telegram` transitioned from being a one-file utility to a project on its own, good coding practices should be followed.  
Split the (*almost 1000 lines*) file into separate classes.

**Comment by DmytroLitvinov** [comment]
@lorcalhost , I guess we can make the same way of architecture as `binance-trade-bot` has. We can run the library module as a script (python3 -m BTB-manager-telegram).

**Comment by lorcalhost** [comment]
I'm afraid transitioning from script to module will break the current bot's version `Update Telegram Bot` feature which currently calls
```python
$(which python3) BTBManagerTelegram.py &
```

We could of course think of a temporary workaround, according to daily clone stats `BTB-manager-telegram` currently has `50` cloners of which `5` cloned today so I suppose not too many people are on the latest version.
</br>
When it comes to multiple class splitting do you have any proposals?  
Would you like to work on this issue?

**Comment by DmytroLitvinov** [comment]
And what exactly it will break? Everything should work or am I missing something after breaking it into the module?

**Comment by lorcalhost** [comment]
`BTB-manager-telegram` currently has an `Update Telegram Bot` feature, when this feature is called the following commands are executed:
```bash
# Kill running instance of BTB-manager-telegram
kill -9 $(ps ax | grep BTBManagerTelegram | fgrep -v grep | awk '{ print $1 }')
# Pull from repo
git pull
# Install new pip requirements (if any)
 $(which python3) -m pip install -r requirements.txt
 # Run BTB-manager-telegram again
 $(which python3) BTBManagerTelegram.py &
```

</br>

If a user using `BTB-manager-telegram` current version were to use this `Update Telegram Bot` feature, `BTB-manager-telegram` would not be automatically restarted, as the new way of launching the bot would be 
```bash
 $(which python3) -m BTB-manager-telegram &
```
