### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#20]
When I started the `BTB-manager-telegram` project my goal was to give easy access to autmated trading to people who are not familiar with terminals and such.  
I had chats with many of this project's users and many of them don't seem to be native english speakers.  
I believe adding mulitple language support will be another step into the right direction and will provide even easier access to automated trading technology to people from anywhere in the world.

**Comment by Lisiadito** [comment]
This could be a useful package to do it: https://pypi.org/project/python-i18n/
What do you think about this? I might be interested to do this change.

**Comment by lorcalhost** [comment]
Hi @Lisiadito , I believe `i18n` is now the standard for localization.  
If you'd like to work on this issue I can assign it to you.  
Sadly in this period I don't have much time to improve `BTB-manager-telegram` myself.

**Comment by Lisiadito** [comment]
I usually work with NodeJs but there we use a i18n package as well so I believe this should not to difficult. I could also add the german translation.

**Comment by lorcalhost** [comment]
Perfect! Thanks for considering contributing to the project.  
I will assign you this issue right away.

**Comment by Lisiadito** [comment]
Ok I managed to get i18n running. Do you mainly want the UI and the messages translated or the logging as well? I think for now leaving the logging in english is fine or?

**Comment by lorcalhost** [comment]
Yes I believe logging in English is fine.
