### ISSUE TITLE
Pin dependencies and integrate DependaBot

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#21]
Better to pin dependencies in `requirements.txt` file and add DependaBot for updating it.

**Comment by lorcalhost** [comment]
Hi, thanks for opening the issue.  
I have never done anything similar but will look into it!

**Comment by lorcalhost** [comment]
@DmytroLitvinov I believe I have correctly set up dependabot, would you mind taking a look?

**Comment by DmytroLitvinov** [comment]
@lorcalhost ,
everything works smoothly: https://github.com/lorcalhost/BTB-manager-telegram/pull/22
