### ISSUE TITLE
Bot doesn't respond to commands after starting the trading bot using the telegram command

### ISSUE THREAD

**Issue by ToTheMoon365** [lorcalhost/BTB-manager-telegram#226]
Hi,
I'm having trouble with the bot when starting the bot with nohup:   python3 -m btb_manager_telegram 
after clicking "Start trade bot" the bot displays the crypto_trading_logger but then stops responding to my commands
I click "Back" but nothing happens. I lose all control unless i kill it terminal and restart again and hit the stop bot  then i get successfully close the bot , using tag [v1.1.1](https://github.com/HaidarWahid/BTB-manager-telegram/releases/tag/v1.1.1)

Related to  [#138](https://github.com/lorcalhost/BTB-manager-telegram/issues/138)

**Comment by MasaiasuOse** [comment]
Can you share the log?

**Comment by HaidarWahid** [comment]
This is the first time when i start and run the bot , and try to close , not getting logs when hitting the close bot 
![starting ](https://user-images.githubusercontent.com/75916143/148988994-83d60bfb-5f05-4cc9-ab4a-fa7563a78062.png)

after restarting ...
![restart](https://user-images.githubusercontent.com/75916143/148989145-257733c5-4fa4-4063-9c04-a2d79dfb8cad.png)

**Comment by MasaiasuOse** [comment]
What about of the log in terminal? `tail -f nohup.out`
Can I ask which fork of the binance-trade-bot do you use? :D

**Comment by ToTheMoon365** [comment]
Im using this [fork ](https://github.com/edeng23/binance-trade-bot)

**Comment by titulebolide** [comment]
@ToTheMoon365 were you able to retreive your logs?

**Comment by ToTheMoon365** [comment]
I'm sorry I could not, could you please give me a guide, much appreciated!

**Comment by MasaiasuOse** [comment]
Go in the terminal in the folder of the btb manager and type this: `tail -f nohup.out`.

**Comment by ToTheMoon365** [comment]
![Screenshot 2022-01-14 153830](https://user-images.githubusercontent.com/75916143/149533250-963c3243-8530-46a7-a90c-b9f41c3c3922.png)

Should I run nohup first to generate the nohup.out? any ideas? 
Thank you for bearing with me !

**Comment by ToTheMoon365** [comment]
> ![Screenshot 2022-01-14 153830](https://user-images.githubusercontent.com/75916143/149533250-963c3243-8530-46a7-a90c-b9f41c3c3922.png)
> 
> Should I run nohup first to generate the nohup.out? any ideas? Thank you for bearing with me !

once I start the bot , no button regist anymore 
![Screenshot 2022-01-14 162753](https://user-images.githubusercontent.com/75916143/149540935-381b1030-0912-4bd9-a857-830fd19be093.png)

**Comment by MasaiasuOse** [comment]
I suggest to use a VPS with a Linux distro. The bot can have permission issues with other OS. Especially when stopping/starting the bot

**Comment by ToTheMoon365** [comment]
> VPS

Im using windows 11

**Comment by MasaiasuOse** [comment]
As I said use a VPS with Linux. As far as I know the trading bot stops the telegram bot on Windows when you start it with the telegram bot.
Oracle Cloud offers multiple free instances for example

**Comment by ToTheMoon365** [comment]
Is there any documentation on how to set it up with vps, because I have no knowledge about the concept

**Comment by MasaiasuOse** [comment]
You can use [this](https://docs.google.com/document/d/1oPz4lvjsIxjAggByRwu3SiEx_aakIfgcScn8SUA0avk/edit) guide.

**Comment by ToTheMoon365** [comment]
Thank you very much

**Comment by MasaiasuOse** [comment]
You are welcome. If you have any further questions, we will be happy to answer them.
Please let us know if it works so we can close this issue.

**Comment by ToTheMoon365** [comment]
@MasaiasuOse  everything works now, Thanks for all the support !
