### ISSUE TITLE
main py file is missing + Maintenance is gone ?

### ISSUE THREAD

**Issue by techn0tr0ll** [lorcalhost/BTB-manager-telegram#243]
Hey there

i dont assume that it is a wanted "feature" that the main python file "BTBManagerTelegram.py" file is gone from official repo and also from the newest release ...

Also the Button "Maintenance" in the Bot is gone and its not possible anymore to update the bots through the telegram bot ... 

is this really intended ?

**Comment by titulebolide** [comment]
The deletion of the py file is intentional, it was a relic from the earliest stages of the btb.if it broke your install, have a look to the installation manual how to start the bot

For the maintenance button, it is still there! Maybe you're on computer and you need to scroll on the buttons to see the hidden ones?

**Comment by techn0tr0ll** [comment]
py file was intentional ?  
according to the readme this file is used to start the bot ... ?!

Nope, the button is not there - not on the mobile nor on the desktop

**Comment by titulebolide** [comment]
The file is not used. The start command :
```
python3 -m btb_manager_telegram
```

**Comment by titulebolide** [comment]
Are you on the latest version of the bot? Are you using a translation?

**Comment by techn0tr0ll** [comment]
okay that was weird ...
i just pulled the repo again and started the bot with  'python3 -m btb_manager_telegram' - didn't notice this way of starting the bot

now it's up and running and the maintenance option is back again ... 😕 

thx for your quick response @titulebolide  and sorry for opening the issue 🤦

**Comment by titulebolide** [comment]
No worries I thought it would bother nobody the removal of this file. Glad to know it's working :)
