### ISSUE TITLE
Next_Coin tabularize size adjustment - Cosmetic

### ISSUE THREAD

**Issue by markkastoun** [lorcalhost/BTB-manager-telegram#248]
In the Next Coin output, the % column is 1 width narrow, making anything after 100.XX appear as 100.**..**
┌−−−−−−┬−−−−−−−┬−−−−−−−−┬−−−−−−−−┐
│ Coin │ %     │Current │Target  │
│      │       │price   │price   │
├−−−−−−┼−−−−−−−┼−−−−−−−−┼−−−−−−−−┤
│ BTT  │ 100.… │0.002777│0.002782│

By modifying buttons.py Line 287 and adding 1 more width, we will get the whole number displayed.
Before            [6, 7, 8, 8],
After               [6, **8**, 8, 8],

Result
┌−−−−−−┬−−−−−−−−┬−−−−−−−−┬−−−−−−−−┐
│ Coin │ %      │Current │Target  │
│      │        │price   │price   │
├−−−−−−┼−−−−−−−−┼−−−−−−−−┼−−−−−−−−┤
│ BTT  │ 100.18 │0.002777│0.002782│

https://github.com/lorcalhost/BTB-manager-telegram/blob/2d6d657c73fdfb7082a9e205b070e96e00474015/btb_manager_telegram/buttons.py#L287

**Comment by titulebolide** [comment]
Why not, the thing is 100% is not supposed to be showing up! But yeah why not
