### ISSUE TITLE
Python Code Quality

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#25]
Integrate `black` and `isort` as minimum.
Also, we can add `flake8` with plugins.

**Comment by lorcalhost** [comment]
@DmytroLitvinov 
It's the first time I hear about those 3 modules, thanks again for teaching me good practices.  
If I understand correctly what you mean by _integrating_ `black` and `isort` is running the following commands on the `BTBManagerTelegram.py` file, correct?

```console
$ python3 -m black BTBManagerTelegram.py
$ python3 -m isort BTBManagerTelegram.py
```

**Comment by DmytroLitvinov** [comment]
@lorcalhost , it is just for keeping our codebase of the library in a clean state.
For using `isort` there is [another way](https://pycqa.github.io/isort/docs/quick_start/2.-cli/) in CLI

It is not required for that type of project I guess, but it is nice to have a feature :)
And in the future we can provide it in CI for checking that contributors follow coding guidelines.

**Comment by lorcalhost** [comment]
@DmytroLitvinov 
That seems very useful.
I also have no experience with CI, would you be able to help me out in implementing this small `black` and `isort` format checking feature?

**Comment by DmytroLitvinov** [comment]
@lorcalhost , sure.
But can't guarantee that I will do it in near feature. 
Maybe tomorrow I will start work on that.

**Comment by lorcalhost** [comment]
@DmytroLitvinov 
Thank you, I will also start attempting on my own, you will find my progress in the [ci_contributions branch](/lorcalhost/BTB-manager-telegram/tree/ci_contributions)

**Comment by lorcalhost** [comment]
@DmytroLitvinov I believe I have succesfully managed to implement the workflow.  
Plase check if everything is correct and tell me if you have any improvement suggestions when you are free. :)
