### ISSUE TITLE
The Biance_trade_bot is not working properly with VPN, and the connection always times out

### ISSUE THREAD

**Issue by lyk199343** [lorcalhost/BTB-manager-telegram#253]
Hello! I don't have direct access to Binance, but I can browse and trade on Biannce via VPN. However, it seems that Biance_trade_bot is not working properly with VPN, and the connection always times out. Is there a good solution for this problem?

  ```
File "C:\ProgramData\Anaconda3\envs\BTB_2\lib\site-packages\requests\adapters.py", line 513, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/ping (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1112: The handshake operation timed out')))
```

**Comment by titulebolide** [comment]
We won't support windows whatsoever. 
On your answer to @MasaiasuOse, you told him " I have tried VPS located in Japan,Hongkong, US and German, without changing the system agent and using the global mode."
I think you are mixing VPS and VPN. VPN (or proxies) is not supposed to be supported. We are talking about deploying the binance trade bot on a VPS, a Virtual Private Server, which is a linux server running in another part of the world.
