### ISSUE TITLE
CRITICAL - Binance Trade Bot config file cannot be found at `../binance-trade-bot/user.cfg`

### ISSUE THREAD

**Issue by jbrepogmailcom** [lorcalhost/BTB-manager-telegram#258]
I have cloned BTB... to folder home/user/binance-trade-bot and starting "python3 -m btb_manager_telegram" in that BTB... folder. The user.cfg is everywhere. Where should it be exactly?

**Comment by titulebolide** [comment]
I think it cannot find the whole binance-trade-bot folder.
by default, your file structure should look like:
```
/home/user
├── binance-trade-bot
└── BTB-manager-telegram
```
If I understand correctly, the BTB-manager-telegram is currently located **in** hte binance-trade-bot folder, which is wrong.

**Comment by jbrepogmailcom** [comment]
OK I had to install BTB in parallel to treding_bot, not inside
