### ISSUE TITLE
Question: Is fork correctly recognized when updating binance trade bot?

### ISSUE THREAD

**Issue by jbrepogmailcom** [lorcalhost/BTB-manager-telegram#265]
Hello. When BTB detects update and updates binance trade bot to new version, does it correctly recognize which fork is updated? There are at least 3 different forks that have different flavours of config file. If one fork is overwritten by other fork during update, config file may cause it will not work correctly or will not work at all.

**Comment by titulebolide** [comment]
Short answer : yes
Long answer : the update is no more complicated than a git pull, so it's fork agnostic
