### ISSUE TITLE
BTB still shows that update is available, even after update

### ISSUE THREAD

**Issue by jbrepogmailcom** [lorcalhost/BTB-manager-telegram#268]
Hello. I get telegram message that binance trade bot update is available and when I check in Maintenance, it says so as well. So I click on update, get message that I should wait a few seconds. After that, if I click on Update, I still get message that update is available.

It seems that updating does not work. Can the telegram bot show message that update was successful? What are prerequisites for update? I use masa's fork, not the original one. Jan

**Comment by titulebolide** [comment]
The update should work fine with masa's fork.
So when you update, you don't see the bot restarting after a while? You should be seeing the welcome message like `Hi username! Welcome to Binance Trade Bot Manager Telegram`.
If not it means the update has actually failed. The update is a quite sensitive part of the program, and is known to fail easily, even if I try to harden it with revisions.
Do you run the manager with nohup of as a service?
Are you able to access the manager's logs?

**Comment by jbrepogmailcom** [comment]
It worked now
