### ISSUE TITLE
Add option to run bot with screen/Docker

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#3]
As user @Brackyt suggested on Discord, add option to run the bot using `screen`/`Docker` instead of directly running with `python`/`nohup`

**Comment by NovusEdge** [comment]
I would like to take this one up if no one's assigned.

**Comment by NovusEdge** [comment]
@lorcalhost I would like to ask about how you want the bot to run with Docker
Please do specify the details.
Also, are there any rules to adhere to for the code?

**Comment by lorcalhost** [comment]
@NovusEdge You are free to do what you wish code-wise.  
This improvement was suggested by a Discord server member and I do not have much experience with Docker nor screen.  
</br>

Building a Docker image for the bot could help solve the issue mentioned in #5 where if the bot is run on Windows the permissions are incorrect for performing some operations.
</br>

Are inter-docker-image permitted?  
If not we could modify the dockerfile from [Binance Trade Bot](https://github.com/edeng23/binance-trade-bot)'s repo so both bots run in the same image, otherwise we need to figure our how inter-image operations such as killing the trade bot's process can be performed
