### ISSUE TITLE
Current Ratios not working

### ISSUE THREAD

**Issue by hippalectryon-0** [lorcalhost/BTB-manager-telegram#37]
Clicking on "current ratios" outputs " Something went wrong, unable to generate ratios at this time."

![image](https://user-images.githubusercontent.com/6502864/114088994-edbcad80-98b5-11eb-916a-2e717bb3cd3b.png)

It never worked so far for me so I'm not sure how to replicate it. Please ask me for specific logs if you think it will help pinpoint the cause.

**Comment by lorcalhost** [comment]
Would you mind sharing your database file?  
The bot has a built-in feature for database file export.  
The database does not contains personal tokens or information but only your trade history as possibly "private data".  
</br>

If you are willing to share the file please send it to `超人力霸王#3802` on Discord.

**Comment by lorcalhost** [comment]
As discussed on Discord this seems to be due to the `scout_history` table always being empty when logging in _Binance Trade Bot_ is explicitly disabled.

**Comment by DmytroLitvinov** [comment]
I have the same issue.
But the error inside the Python code somewhere:

> 2021-05-12 19:07:25,896 - btb_manager_telegram_logger - ERROR - ❌ Something went wrong, unable to generate ratios at this time: list index out of range

**Comment by DmytroLitvinov** [comment]
I just added `exc_info=True` to logger.error to see traceback of error and found the line on which that error happens:
2021-05-12 19:18:06,988 - btb_manager_telegram_logger - ERROR - ❌ Something went wrong, unable to generate ratios at this time: list index out of range
Traceback (most recent call last):
  File "/home/manager/binance-trade-bot/BTB-manager-telegram/btb_manager_telegram/buttons.py", line 199, in current_ratios
    last_update = datetime.strptime(query[0][0], "%Y-%m-%d %H:%M:%S.%f")
IndexError: list index out of range

**Comment by chchia** [comment]
i am too having current ratio not working problem.

i checked the db, the scout_history tables is having 1million ++ of record but all value is completely empty.

can someone guide me how to resolve?
