### ISSUE TITLE
Wrong ratios on past transactions

### ISSUE THREAD

**Issue by hippalectryon-0** [lorcalhost/BTB-manager-telegram#38]
Potentially linked to #35 

On "Current Value", wrong ratios are displayed for the previously bough ratios.

![image](https://user-images.githubusercontent.com/6502864/114089246-32484900-98b6-11eb-863f-5cc99cf51518.png)

As we can see, the bot thinks doge was at 0.03, but the value hasn't changed much from 0.06 lately (the bot only ran for a few hours). This may be due to me buying coins, stopping the bot, manually doing some transactions which changed the coin's amount, then resuming the bot. I'm not sure how the ratio is computed, but it might be that the bot assumes that the amount did not change when computing the old ratio instead of directly storing the old ratio.

**Comment by lorcalhost** [comment]
The exchange ratio when purchased is calculated as `(buy_price / balance)` where `balance` is the current one.  
This issue can be quickly fixed by querying `alt_trade_amount` from the `trade_history` table and calculating the ratio as calculating it as `(buy_price / alt_trade_amount)`.
