### ISSUE TITLE
Add support of multiple instance of bots

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#42]
Let's imagine that we have installed 2nd bot on the same VPS server.
So right now when we will try to stop bot from 2nd bot, it will stop also from 1st bot.
More details about impelemention of [finding and killing processes](https://github.com/lorcalhost/BTB-manager-telegram/blob/0cd9256fdc08bbefcd740b829b00c234fd03f1c0/btb_manager_telegram/utils.py#L79) which is used in [stop_bot function](https://github.com/lorcalhost/BTB-manager-telegram/blob/0cd9256fdc08bbefcd740b829b00c234fd03f1c0/btb_manager_telegram/buttons.py#L281)

**Comment by lorcalhost** [comment]
This seems like a big feature to implement.  
By multiple bot instances support do you just mean killing only one of the two instances or add full ability to switch and control both from telegram?  

If we just manage to distinguish the killing the user could create two telegram bots and manage them saparately that way.

**Comment by DmytroLitvinov** [comment]
Each binance-trade-bot should have its own telegram bot.
So when I like in BinanceTradeBot1 it should kill first bot of binance-trade-bot and it should not touch process of 2nd bot.

So we should know that we are killing the process from a folder of `settings.ROOT_PATH` variable and not all processes of binance-trade-bot.

So for that case we are getting all of processes and check with `pwdx` [command](https://linux.die.net/man/1/pwdx) that specific PID is related to BTB-manager-telegram.

**Comment by lorcalhost** [comment]
We should also be managing process killing before updates of not only `Binance Trade Bot` but also `BTB Manager Telegram`.
