### ISSUE TITLE
Can't Find apprise.yml

### ISSUE THREAD

**Issue by deancarloz** [lorcalhost/BTB-manager-telegram#44]
Hi,

Both my folders (bot and telegram bot) are in the same drectory:
![image](https://user-images.githubusercontent.com/21025022/114380645-35775980-9b82-11eb-858d-57c165c69705.png)
The teleram bot can't find de yml file inside the config directory:
![image](https://user-images.githubusercontent.com/21025022/114380748-53dd5500-9b82-11eb-80ef-449df71806ec.png)

I dont see why it cant find it since I'm running the binance bot with the consiguration for the telegram bot and it working.

Any Idead why thats not working?

**Comment by lorcalhost** [comment]
This seems to be a bug affecting windows regarding how we currently handle path joining.  
I will look into it and push a fix asap

**Comment by DmytroLitvinov** [comment]
@lorcalhost , here is where the problem: https://github.com/lorcalhost/BTB-manager-telegram/blob/d69e7a9acdb0519b87da9f8a74f14dc484c088af/btb_manager_telegram/utils.py#L23
We were talking about that recently ;)

**Comment by deancarloz** [comment]
Hi, I solve by indicating the full path to the bot when run it through:
python -m BTB-manager-telegram-main -p {full path}

**Comment by lorcalhost** [comment]
@DmytroLitvinov Line `23` *should* theoretically be correct but I think you are right, using `os.path.join()` will ensure we have no trouble.  

@deancarloz I just pushed an update to the repo, can you please test if you are still experiencing the same problem?

**Comment by deancarloz** [comment]
@lorcalhost just tested, still unable.
![image](https://user-images.githubusercontent.com/21025022/114383263-470e3080-9b85-11eb-883e-c1f62de3aa05.png)

**Comment by lorcalhost** [comment]
@deancarloz 
I believe this actually seems related to how your cloning tool is naming directories.  
- `binance-trade-bot-master` should actually be called `binance-trade-bot`  
- `BTB-manager-telegram-main` should actually be called `BTB-manager-telegram`  

What tool are you using to clone the two repositories?

**Comment by deancarloz** [comment]
Ah ok,

I'm actualy just download in as zip and unziping it into the directory
