### ISSUE TITLE
Improve constant for truncating text

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#45]
Right now it is not clear why do we have `4096` and not `5014` or another number.
We need to refactor that line https://github.com/lorcalhost/BTB-manager-telegram/blob/0c28f4d35bf2255f880861194766ffb058b882b0/btb_manager_telegram/utils.py#L64 with using `telegram.constants.MAX_MESSAGE_LENGTH` and of course rename function (something like `telegram_text_truncator`)

**Comment by lorcalhost** [comment]
I see that in #47 you found [a built-in constant](https://python-telegram-bot.readthedocs.io/en/stable/telegram.constants.html#telegram.constants.MAX_MESSAGE_LENGTH) that takes the value 4096.
