### ISSUE TITLE
Add logging for errors

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#46]
Right now when I click on "Current ratios" I receive an error.
When I am trying to checkout logs from `nohup.out` - there is no logging for the error.

So I manually added logging error and checked the error - I got: `list index out of range`. But this is another issue I guess related to  function `text_4096_cutter` https://github.com/lorcalhost/BTB-manager-telegram/blob/0c28f4d35bf2255f880861194766ffb058b882b0/btb_manager_telegram/utils.py#L60

**Comment by lorcalhost** [comment]
Do you propose using `logger.error` and `logger.warning` to log errors and warnings or do you have other solutions in mind?

**Comment by DmytroLitvinov** [comment]
`logger.warning` and `logger.error` should be enough.
