### ISSUE TITLE
Update Binance API

### ISSUE THREAD

**Issue by Dan-Wood** [lorcalhost/BTB-manager-telegram#49]
Since you've got a mechanism to update both this manager and the bot itself, perhaps we should be monitoring the Binance API package as well?

http://github.com/sammchardy/python-binance.git

`pip install --upgrade --no-deps --force-reinstall git+git://github.com/sammchardy/python-binance.git`

**Comment by DmytroLitvinov** [comment]
This is not an issue of that package.
You need to go to binance-trade-bot and ask them to add the latest supported PyPi package into requirements.txt file.

**Comment by lorcalhost** [comment]
@Dan-Wood 
As Dmytro said, this is not a dependency for `BTB-manager-telegram`.  
If _Binance Trade Bot_ ever changes `python-binance` version in their `requirements.txt` file `BTB-manager-telegram` will automatically upgrade to that version.
