### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by phoenix-blue** [lorcalhost/BTB-manager-telegram#5]
Hello,

Follow the instructions and run the script, first part is working (connection with Telegram).
But when there must be a interaction with the binance trader bot I get a permission error.

`2021-03-29 20:48:29,614 - telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\psutil\_pswindows.py", line 780, in cmdline
    ret = cext.proc_cmdline(self.pid, use_peb=True)
PermissionError: [WinError 5] Access denied: '(originated from OpenProcess)'`

I have already try to run with the admin rights but unfortunately it doesn't work.
Are there any suggestions to try?

Thanks a lot.

**Comment by lorcalhost** [comment]
I have not thoroughly tested the program on Windows.  
You might try executing the bot in a Python `virtualenv`  as that gives full permissions for all files inside of it.

**Comment by phoenix-blue** [comment]
virtualenv gives me a error, but the WSL solution did the trick.
didn't even know about it, thank you very much!

**Comment by lorcalhost** [comment]
No problem, enjoy the bot!  
I will do a bit more testing on Windows but as of now I will advise using WSL on the `README.md` file.
