### ISSUE TITLE
Add a feature to purge trade bot logs

### ISSUE THREAD

**Issue by pwnfoo** [lorcalhost/BTB-manager-telegram#57]
TSIA

The logs can sometimes eat up a lot of space, so it'll be nice to have a way to purge logs. 

Maybe this can be coupled with Delete Database? I don't know if there's a valid use case where you will want to purge db, but not the logs.

**Comment by lorcalhost** [comment]
You are referring to `Binance Trade Bot's logs`, correct?

**Comment by DmytroLitvinov** [comment]
Seems like so ;)

**Comment by pwnfoo** [comment]
> You are referring to _Binance Trade Bot_'s logs, correct?

Correct, updated title :)
