### ISSUE TITLE
Allow multiple users to interact with the telegram bot

### ISSUE THREAD

**Issue by pwnfoo** [lorcalhost/BTB-manager-telegram#58]
It'll be great if the bot can respond to multiple people, in a group, etc.

**Comment by lorcalhost** [comment]
I guess we could add a `-g` flag as launch option and then differentiate the filter here:
https://github.com/lorcalhost/BTB-manager-telegram/blob/ca3a6fe3fbea0d625137fc0cb2e05e03c21a94ee/btb_manager_telegram/handlers.py#L411-L413

**Comment by lorcalhost** [comment]
It was easier than expected, I just had to change the filter type.  

Went from:
```python
Filters.user(user_id=eval(settings.USER_ID)
```
to
```python
Filters.chat(chat_id=eval(settings.CHAT_ID))
```

**Comment by pwnfoo** [comment]
@lorcalhost Perfect! I was testing this out and noticed that each user has to type `/start` in the group before they can interact with the bot.

Is this intended behaviour? If so, I created #59 adding info about this.

**Comment by lorcalhost** [comment]
@pwnfoo this works as intended.  
The bot is currently build using Telegram's `ConversationHandler` which behaves this way.
