### ISSUE TITLE
Use correlation matrix to automatically populate coin list

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#60]
Use [this project](https://github.com/madnesspie/binance-correlation-matrix) by user @madnesspie to automatically populate the `supported_coin_list` file with good coins.

**Comment by lorcalhost** [comment]
An updated version of the project by user @kentwar can be found [here](https://github.com/kentwar/binance_correlation_script).

**Comment by lorcalhost** [comment]
To improve compatibility and execution times a coin list should be generated every X minutes/hours through a GitHub Action which updates a gist in json/txt format.  

The client will then be able to fetch the gist and read the coin list from it.

**Comment by kentwar** [comment]
I don't know much about gists, but calling the data requires an api key. It's possible to keep the script that makes the gist private but the gist is public?

**Comment by lorcalhost** [comment]
@kentwar Yes that is absolutely possible using Github Actions [secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).  

If you are unfamiliar with this I can host it on the `BTB-manager-telegram` repository otherwise if you prefer I can help you setting it up on your repo.

**Comment by kentwar** [comment]
I've got lots of work on this week, so you can host it if you like. I'll of course help out where I can.

**Comment by titulebolide** [comment]
This issue can be close as it has been decided not to bring this functionnality to the bot
