### ISSUE TITLE
`Start bot` not working when full path is passed as argument

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#61]
If a full path (e.g. `/root/bot/install/dir`) is passed as argument `-p` instead of a relative one (e.g. `../bot/install/dir`) `BTBMT` is unable to start `BTB`.

It might be due to this function:
https://github.com/lorcalhost/BTB-manager-telegram/blob/50932ec8a21169828985ff9db359b45b00aa1be9/btb_manager_telegram/utils.py#L75-L86

@DmytroLitvinov do you know more about this?

**Comment by DmytroLitvinov** [comment]
@lorcalhost , from brief checking everything, should work as expected.

**Comment by lorcalhost** [comment]
@DmytroLitvinov this bug was reported by a user on Discord.  
When he entersthe full path the bot is unable to start BTB. 🤔

**Comment by lorcalhost** [comment]
I can confirm this is an issue.
