### ISSUE TITLE
Calculation of current ratios is hard coded

### ISSUE THREAD

**Issue by DmytroLitvinov** [lorcalhost/BTB-manager-telegram#88]
Current calculation of [current ratios is hardcoded (0,001 * 5)](https://github.com/lorcalhost/BTB-manager-telegram/blob/main/btb_manager_telegram/buttons.py#L194) and it should be gotten from user.cfg file according to [the method of _get_ratios of binance-trade-bot](https://github.com/edeng23/binance-trade-bot/blob/0de5573059ca8058aa6ea9c7fcbe14b890290f31/binance_trade_bot/auto_trader.py#L107).

**Comment by eudora-fabia** [comment]
@DmytroLitvinov  does this mean it could be displaying the wrong ratio if user.cfg is not in default?

**Comment by DmytroLitvinov** [comment]
@eudora-fabia , yes.
