### ISSUE TITLE
Dockerfile may break if the script is run from a directory other than the project-directory

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#9]
This may break if the script is run from a directory other than the project-directory.

A solution to this may be using `os` and `pathlib` to change the path to the project-directory.

_Originally posted by @NovusEdge in https://github.com/lorcalhost/BTB-manager-telegram/pull/7#discussion_r605022377_

**Comment by NovusEdge** [comment]
May I take this issue up?

**Comment by lorcalhost** [comment]
Of course @NovusEdge , you are the Docker expert here 😄

**Comment by NovusEdge** [comment]
> Of course @NovusEdge , you are the Docker expert here 😄

I would rather not call myself a docker `expert` 😅 ,  but sure
