### ISSUE TITLE
Progress Btn - Unable to fetch progress information from database: type NoneType doesn't define __round__ method

### ISSUE THREAD

**Issue by eudora-fabia** [lorcalhost/BTB-manager-telegram#90]
BTB-manager-telegram master branch e71dea6
btb - using this from this [PR](https://github.com/edeng23/binance-trade-bot/pull/328/commits/0477f97c4182c3d641ef3d43fbf8d44b7d1fff38)

Action1 : Click on progress button

```
ERROR - ❌ Unable to fetch progress information from database: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/root/BTB-manager-telegram/btb_manager_telegram/buttons.py", line 144, in check_progress
    f"*{coin[0]}*\n"
TypeError: type NoneType doesn't define __round__ method
```

Action 2: Click on Current value button

```
ERROR - ❌ Something went wrong, unable to generate value at this time: type NoneType doesn't define __round__ method
Traceback (most recent call last):
  File "/root/BTB-manager-telegram/btb_manager_telegram/buttons.py", line 89, in current_value
    f"\nLast update: `{last_update.strftime('%H:%M:%S %d/%m/%Y')}`\n\n"
TypeError: type NoneType doesn't define __round__ method
```

**Comment by eudora-fabia** [comment]
It works fine after I restarted from a fresh db.

**Comment by adamwojt** [comment]
I am having same issue. I assume this is because there hasn't been any trades yet. Could that be right?
![image](https://user-images.githubusercontent.com/45100954/118411612-0a5eb900-b69e-11eb-8bfc-fbaddfc8948e.png)

**Comment by lorcalhost** [comment]
> I am having same issue. I assume this is because there hasn't been any trades yet. Could that be right?
> ![image](https://user-images.githubusercontent.com/45100954/118411612-0a5eb900-b69e-11eb-8bfc-fbaddfc8948e.png)
> 

That sounds about right, wait until the bot has made its first trade (therefore populating the database) and let me know if you still encounter this issue :)
