### ISSUE TITLE
Send changelog message after update

### ISSUE THREAD

**Issue by lorcalhost** [lorcalhost/BTB-manager-telegram#94]
After updating `btb-manager-telegram` or `binance-trade-bot` the telegram bot should be able to send a detail changelog of the update.  

This could be done by fetching the changes from the git commit messages / descriptions.  

`git whatchanged ..origin` can be used after fetching.

**Comment by titulebolide** [comment]
I close this in favor of #187 , where we can provide the changelog in the tag
